In [14]:
from nba_api.stats.endpoints import playbyplayv3, leaguegamefinder
from nba_api.stats.static import teams
import pandas as pd

pd.set_option('display.max_columns', None)

In [8]:
lakers = [t for t in teams.get_teams() if t['full_name'] == 'Los Angeles Lakers'][0]
lakers_id = lakers['id']
print(lakers_id)

1610612747

In [9]:
gamefinder = leaguegamefinder.LeagueGameFinder(
    team_id_nullable=lakers_id,
    season_nullable='2025-26',
    season_type_nullable='Regular Season',
    league_id_nullable='00'
)

games = gamefinder.get_data_frames()[0]
print(games.shape)

(82, 28)

In [10]:
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612747,LAL,Los Angeles Lakers,0022501198,2026-04-12,LAL vs. UTA,W,240,131,51,93,0.548,15,34,0.441,14,17,0.824,11,38,49,37,12,6,15,20,24.0
1,22025,1610612747,LAL,Los Angeles Lakers,0022501185,2026-04-10,LAL vs. PHX,W,241,101,35,69,0.507,8,20,0.400,23,30,0.767,4,31,35,27,17,3,11,18,28.0
2,22025,1610612747,LAL,Los Angeles Lakers,0022501170,2026-04-09,LAL @ GSW,W,243,119,49,80,0.613,16,29,0.552,5,8,0.625,8,25,33,37,14,3,17,13,16.0
3,22025,1610612747,LAL,Los Angeles Lakers,0022501155,2026-04-07,LAL vs. OKC,L,242,87,32,73,0.438,9,26,0.346,14,31,0.452,8,30,38,26,7,3,17,12,-36.0
4,22025,1610612747,LAL,Los Angeles Lakers,0022501140,2026-04-05,LAL @ DAL,L,240,128,47,91,0.516,8,27,0.296,26,33,0.788,11,38,49,36,6,1,12,23,-6.0

In [12]:
game_id = games.iloc[0]['GAME_ID']
print(game_id)

0022501198

In [15]:
pbp = playbyplayv3.PlayByPlayV3(game_id=game_id).get_data_frames()[0]
print(pbp.shape)
print(pbp.columns.tolist())

(499, 24)
['gameId', 'actionNumber', 'clock', 'period', 'teamId', 'teamTricode', 'personId', 'playerName', 'playerNameI', 'xLegacy', 'yLegacy', 'shotDistance', 'shotResult', 'isFieldGoal', 'scoreHome', 'scoreAway', 'pointsTotal', 'location', 'description', 'actionType', 'subType', 'videoAvailable', 'shotValue', 'actionId']

In [16]:
pbp.head()

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0022501198,2,PT12M00.00S,1,0,,0,,,0,0,0,,0,0,0,0,,Start of 1st Period (8:41 PM EST),period,start,1,0,1
1,0022501198,4,PT12M00.00S,1,1610612747,LAL,1629028,Ayton,D. Ayton,0,0,0,,0,,,0,h,Jump Ball Ayton vs. Tshiebwe: Tip to L. James,Jump Ball,,1,0,2
2,0022501198,7,PT11M45.00S,1,1610612747,LAL,1628379,Kennard,L. Kennard,-98,153,18,Made,1,2,0,2,h,Kennard 18' Pullup Jump Shot (2 PTS) (L. James...,Made Shot,Pullup Jump shot,1,2,3
3,0022501198,10,PT11M41.00S,1,1610612762,UTA,1642846,Bailey,A. Bailey,-81,233,25,Missed,1,,,0,v,MISS Bailey 25' 3PT Pullup Jump Shot,Missed Shot,Pullup Jump shot,1,3,4
4,0022501198,11,PT11M38.00S,1,1610612762,UTA,1642396,Hinson,B. Hinson,0,0,0,,0,,,0,v,Hinson REBOUND (Off:1 Def:0),Rebound,Unknown,1,0,5

In [17]:
pbp['actionType'].value_counts()

actionType
Rebound           108
Missed Shot        95
Made Shot          92
Free Throw         44
                   35
Foul               34
Substitution       34
Turnover           33
Timeout            11
period              8
Jump Ball           2
Instant Replay      2
Heave               1
Name: count, dtype: int64

In [18]:
pbp[pbp['actionType'] == 'Free Throw']

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
33,0022501198,45,PT08M11.00S,1,1610612747,LAL,1629060,Hachimura,R. Hachimura,0,0,0,,0,,,0,h,MISS Hachimura Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,34
35,0022501198,47,PT08M11.00S,1,1610612747,LAL,1629060,Hachimura,R. Hachimura,0,0,0,,0,11,6,17,h,Hachimura Free Throw 2 of 2 (3 PTS),Free Throw,Free Throw 2 of 2,1,0,36
39,0022501198,52,PT07M48.00S,1,1610612747,LAL,203935,Smart,M. Smart,0,0,0,,0,12,6,18,h,Smart Free Throw 1 of 2 (1 PTS),Free Throw,Free Throw 1 of 2,1,0,40
40,0022501198,53,PT07M48.00S,1,1610612747,LAL,203935,Smart,M. Smart,0,0,0,,0,13,6,19,h,Smart Free Throw 2 of 2 (2 PTS),Free Throw,Free Throw 2 of 2,1,0,41
44,0022501198,61,PT07M16.00S,1,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,15,9,24,v,Tshiebwe Free Throw 1 of 2 (3 PTS),Free Throw,Free Throw 1 of 2,1,0,45
46,0022501198,64,PT07M16.00S,1,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,15,10,25,v,Tshiebwe Free Throw 2 of 2 (4 PTS),Free Throw,Free Throw 2 of 2,1,0,47
65,0022501198,87,PT05M20.00S,1,1610612762,UTA,1642846,Bailey,A. Bailey,0,0,0,,0,,,0,v,MISS Bailey Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,66
69,0022501198,93,PT05M20.00S,1,1610612762,UTA,1642846,Bailey,A. Bailey,0,0,0,,0,,,0,v,MISS Bailey Free Throw 2 of 2,Free Throw,Free Throw 2 of 2,1,0,70
74,0022501198,99,PT04M47.00S,1,1610612747,LAL,1628379,Kennard,L. Kennard,0,0,0,,0,,,0,h,MISS Kennard Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,75
76,0022501198,101,PT04M47.00S,1,1610612747,LAL,1628379,Kennard,L. Kennard,0,0,0,,0,22,12,34,h,Kennard Free Throw 2 of 2 (3 PTS),Free Throw,Free Throw 2 of 2,1,0,77
79,0022501198,106,PT04M03.00S,1,1610612747,LAL,1629060,Hachimura,R. Hachimura,0,0,0,,0,23,14,37,h,Hachimura Free Throw 1 of 2 (4 PTS),Free Throw,Free Throw 1 of 2,1,0,80
80,0022501198,111,PT04M03.00S,1,1610612747,LAL,1629060,Hachimura,R. Hachimura,0,0,0,,0,24,14,38,h,Hachimura Free Throw 2 of 2 (5 PTS),Free Throw,Free Throw 2 of 2,1,0,81
88,0022501198,121,PT03M15.00S,1,1610612762,UTA,1641729,Sensabaugh,B. Sensabaugh,0,0,0,,0,,,0,v,MISS Sensabaugh Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,89
91,0022501198,125,PT03M15.00S,1,1610612762,UTA,1641729,Sensabaugh,B. Sensabaugh,0,0,0,,0,26,15,41,v,Sensabaugh Free Throw 2 of 2 (1 PTS),Free Throw,Free Throw 2 of 2,1,0,92
108,0022501198,150,PT01M38.00S,1,1610612747,LAL,2544,James,L. James,0,0,0,,0,29,17,46,h,L. James Free Throw 1 of 2 (7 PTS),Free Throw,Free Throw 1 of 2,1,0,109
109,0022501198,151,PT01M38.00S,1,1610612747,LAL,2544,James,L. James,0,0,0,,0,30,17,47,h,L. James Free Throw 2 of 2 (8 PTS),Free Throw,Free Throw 2 of 2,1,0,110
112,0022501198,157,PT01M16.00S,1,1610612762,UTA,1641729,Sensabaugh,B. Sensabaugh,0,0,0,,0,30,18,48,v,Sensabaugh Free Throw 1 of 2 (4 PTS),Free Throw,Free Throw 1 of 2,1,0,113
113,0022501198,158,PT01M16.00S,1,1610612762,UTA,1641729,Sensabaugh,B. Sensabaugh,0,0,0,,0,30,19,49,v,Sensabaugh Free Throw 2 of 2 (5 PTS),Free Throw,Free Throw 2 of 2,1,0,114
126,0022501198,174,PT00M08.40S,1,1610612747,LAL,2544,James,L. James,0,0,0,,0,31,22,53,h,L. James Free Throw 1 of 2 (9 PTS),Free Throw,Free Throw 1 of 2,1,0,127
127,0022501198,175,PT00M08.40S,1,1610612747,LAL,2544,James,L. James,0,0,0,,0,32,22,54,h,L. James Free Throw 2 of 2 (10 PTS),Free Throw,Free Throw 2 of 2,1,0,128
147,0022501198,201,PT10M41.00S,2,1610612762,UTA,1641729,Sensabaugh,B. Sensabaugh,0,0,0,,0,35,26,61,v,Sensabaugh Free Throw 1 of 2 (12 PTS),Free Throw,Free Throw 1 of 2,1,0,148
149,0022501198,204,PT10M41.00S,2,1610612762,UTA,1641729,Sensabaugh,B. Sensabaugh,0,0,0,,0,,,0,v,MISS Sensabaugh Free Throw 2 of 2,Free Throw,Free Throw 2 of 2,1,0,150
169,0022501198,226,PT09M39.00S,2,1610612747,LAL,2544,James,L. James,0,0,0,,0,36,26,62,h,L. James Free Throw 1 of 2 (11 PTS),Free Throw,Free Throw 1 of 2,1,0,170
171,0022501198,228,PT09M39.00S,2,1610612747,LAL,2544,James,L. James,0,0,0,,0,,,0,h,MISS L. James Free Throw 2 of 2,Free Throw,Free Throw 2 of 2,1,0,172
188,0022501198,255,PT08M13.00S,2,1610612747,LAL,2544,James,L. James,0,0,0,,0,39,29,68,h,L. James Free Throw 1 of 1 (14 PTS),Free Throw,Free Throw 1 of 1,0,0,189
203,0022501198,278,PT07M06.00S,2,1610612747,LAL,1629028,Ayton,D. Ayton,0,0,0,,0,42,31,73,h,Ayton Free Throw 1 of 2 (9 PTS),Free Throw,Free Throw 1 of 2,0,0,204
206,0022501198,283,PT07M06.00S,2,1610612747,LAL,1629028,Ayton,D. Ayton,0,0,0,,0,43,31,74,h,Ayton Free Throw 2 of 2 (10 PTS),Free Throw,Free Throw 2 of 2,1,0,207
208,0022501198,286,PT06M48.00S,2,1610612762,UTA,1642262,Williams,C. Williams,0,0,0,,0,43,32,75,v,Williams Free Throw 1 of 2 (3 PTS),Free Throw,Free Throw 1 of 2,1,0,209
209,0022501198,287,PT06M48.00S,2,1610612762,UTA,1642262,Williams,C. Williams,0,0,0,,0,43,33,76,v,Williams Free Throw 2 of 2 (4 PTS),Free Throw,Free Throw 2 of 2,1,0,210
300,0022501198,423,PT08M00.00S,3,1610612762,UTA,1643016,Mbeng,B. Mbeng,0,0,0,,0,75,61,136,v,Mbeng Free Throw 1 of 1 (6 PTS),Free Throw,Free Throw 1 of 1,1,0,301
309,0022501198,433,PT07M11.00S,3,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,75,62,137,v,Tshiebwe Free Throw 1 of 2 (13 PTS),Free Throw,Free Throw 1 of 2,1,0,310
310,0022501198,434,PT07M11.00S,3,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,75,63,138,v,Tshiebwe Free Throw 2 of 2 (14 PTS),Free Throw,Free Throw 2 of 2,1,0,311
315,0022501198,444,PT06M38.00S,3,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,,,0,v,MISS Tshiebwe Free Throw 1 of 2,Free Throw,Free Throw 1 of 2,1,0,316
317,0022501198,446,PT06M38.00S,3,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,77,64,141,v,Tshiebwe Free Throw 2 of 2 (15 PTS),Free Throw,Free Throw 2 of 2,1,0,318
390,0022501198,547,PT10M49.00S,4,1610612762,UTA,1642262,Williams,C. Williams,0,0,0,,0,97,77,174,v,Williams Free Throw 1 of 2 (9 PTS),Free Throw,Free Throw 1 of 2,1,0,391
391,0022501198,548,PT10M49.00S,4,1610612762,UTA,1642262,Williams,C. Williams,0,0,0,,0,97,78,175,v,Williams Free Throw 2 of 2 (10 PTS),Free Throw,Free Throw 2 of 2,1,0,392
418,0022501198,585,PT07M13.00S,4,1610612762,UTA,1643016,Mbeng,B. Mbeng,0,0,0,,0,109,86,195,v,Mbeng Free Throw 1 of 2 (11 PTS),Free Throw,Free Throw 1 of 2,1,0,419
422,0022501198,592,PT07M13.00S,4,1610612762,UTA,1643016,Mbeng,B. Mbeng,0,0,0,,0,,,0,v,MISS Mbeng Free Throw 2 of 2,Free Throw,Free Throw 2 of 2,1,0,423
453,0022501198,638,PT04M23.00S,4,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,,,0,v,MISS Tshiebwe Free Throw 1 of 1,Free Throw,Free Throw 1 of 1,1,0,454
468,0022501198,659,PT02M53.00S,4,1610612762,UTA,1643016,Mbeng,B. Mbeng,0,0,0,,0,124,97,221,v,Mbeng Free Throw 1 of 2 (12 PTS),Free Throw,Free Throw 1 of 2,1,0,469
469,0022501198,660,PT02M53.00S,4,1610612762,UTA,1643016,Mbeng,B. Mbeng,0,0,0,,0,,,0,v,MISS Mbeng Free Throw 2 of 2,Free Throw,Free Throw 2 of 2,1,0,470
473,0022501198,666,PT02M22.00S,4,1610612762,UTA,1643060,Gray,H. Gray,0,0,0,,0,127,98,225,v,Gray Free Throw 1 of 2 (5 PTS),Free Throw,Free Throw 1 of 2,1,0,474
474,0022501198,667,PT02M22.00S,4,1610612762,UTA,1643060,Gray,H. Gray,0,0,0,,0,127,99,226,v,Gray Free Throw 2 of 2 (6 PTS),Free Throw,Free Throw 2 of 2,1,0,475
490,0022501198,688,PT01M00.00S,4,1610612762,UTA,1631131,Tshiebwe,O. Tshiebwe,0,0,0,,0,,,0,v,MISS Tshiebwe Free Throw 1 of 1,Free Throw,Free Throw 1 of 1,1,0,491